### ISSUE TITLE
검색 정상화

### ISSUE THREAD

**Issue by jseop-lim** [jseop-lim/jseoplim-profile-hugo#19]
`params.toml`의 아래 부분을 수정했을 때, 검색 결과 클릭한 경로가 undefined인 문제 해결

```toml
[search]
  enable = true
```

<img width="498" alt="image" src="https://github.com/user-attachments/assets/02e957af-83bf-4a7f-98cc-45a4ab55898b" />
